### ISSUE TITLE
Fix account creation on portmap admin some day

### ISSUE THREAD

**Issue by lisad** [dtinit/portmap#109]
This is not very high priority if we can do account creation via command line, but noting here that we should probably fix some day...
https://portmap.dtinit.org/dj-admin/account/emailaddress/add/

**Comment by alexbainter** [comment]
I'm not sure what the email address table is for, but I added @Gogo-ug1 with https://portmap.dtinit.org/dj-admin/core/user/add/ (adding a **user**, not an email)

![image](https://github.com/dtinit/portmap/assets/6510436/9b6c4c87-967f-4562-ab72-3157868098cc)
