### ISSUE TITLE
Switch to a GET request for /find_articles

### ISSUE THREAD

**Issue by alexbainter** [dtinit/portmap#21]
Right now the main article query is making a POST request to find_articles and directing the user to /find_articles. Since we're not creating anything on the backend, this can/should really just be a GET (EDIT: I guess maybe we're creating some sort of analytics entry? But I still think this should be a GET). I _think_ this will also prevent the user from getting this warning when they refresh the article list:
![Screenshot from 2024-02-20 13-15-58](https://github.com/dtinit/portmap/assets/6510436/55a2f865-8a8e-4f7e-b59f-f1c8a1b9b32e)

**Comment by lisad** [comment]
Actually this one is "by design" although we can certainly debate about a better design:  this POSTs the query parameters so the server can save them - we log which kinds of articles are most often queried for.  Technically accurate (the best kind of accurate) POST!

**Comment by alexbainter** [comment]
Yeah, I realized that was probably the case after I wrote this up. I'll think this over some more; switching to a GET request would also resolve #22 while still exposing the parameters to the backend for logging, **unless** the request gets served a cached response before reaching the backend which would obviously be bad for us. In the meantime this warning is probably not a big deal!

**Comment by alexbainter** [comment]
I think since we want to do #21 to make sharable URLs, we will need to switch this to a GET. If a user clicks a URL like `portmap.dtinit.org/find_articles?source=vimeo&destination=youtube`, I'm pretty sure that will always send a GET request. The query parameters will still be accessible to the server so we can still save them, and we should be able to just disable caching on those responses.
