### ISSUE TITLE
Decide on minumum browser support

### ISSUE THREAD

**Issue by alexbainter** [dtinit/portmap#23]
We should decide (and document!) which browsers and versions/% of real-world users we'd like to support, since it informs which browser features we can use. For example, we currently have nested CSS in base.css, but the [support for this is <85% of users based on current browser usage](https://caniuse.com/css-nesting). I think for a content-focused site like this, we should aim to support as many users as reasonably possible; in this specific example, I would suggest we either rewrite our CSS to not use nesting, or we use a preprocessor like SCSS or PostCSS to "unwrap" nested CSS before deployment.

**Comment by lisad** [comment]
Yes I agree, we should move towards supporting more browsers/versions.  Please fix the portmap CSS - do we have similar barriers in dtinit.org's CSS?

**Comment by alexbainter** [comment]
@lisad There is some nested CSS in dtinit.org's source files, but I don't see any actually being served. I would guess Jekyll's build process is rewriting the CSS before deployment, so all good there!
