### ISSUE TITLE
Fix article feedback form reveal

### ISSUE THREAD

**Issue by alexbainter** [dtinit/portmap#36]
Right now the textarea only reveals if you select the frowny face, but doesn't go away if you switch back to the smiley face. Do we want to include the textarea for both positive and negative feedback, or should it only be present for negative feedback?

![image](https://github.com/dtinit/portmap/assets/6510436/f9f03d9e-22be-4570-b959-7100be97ed8f)

**Comment by lisad** [comment]
Sure, I'd love to get feedback even if there's a smiley face. THey might feel generally positive but still point out an issue with the article.
