### ISSUE TITLE
Missing help - should we ask for contribution or omit?

### ISSUE THREAD

**Issue by lisad** [dtinit/portmap#54]
![Screenshot 2024-03-07 at 1 53 18 PM](https://github.com/dtinit/portmap/assets/484337/43c99a35-901b-4275-a0c1-3c19e86c6dc2)

If we add a new content type and forget to add a description of that content type, should we say so here in the popup?

**Comment by alexbainter** [comment]
As of #80, datatypes that don't have a description (ie nothing in https://github.com/dtinit/portability-articles/blob/e4f934c5a9c293e8058aeab1486368049192a0b9/datatype-help.yaml) won't appear in the list. Closing this!
