### ISSUE TITLE
Fix markdown list formatting

### ISSUE THREAD

**Issue by alexbainter** [dtinit/portmap#94]
We thought this was an issue with the markdown (https://github.com/dtinit/portability-articles/issues/29) but it wasn't fixed by https://github.com/dtinit/portability-articles/pull/64 so it must be something to do with our markdown to HTML process

![Screenshot from 2024-05-13 12-37-02](https://github.com/dtinit/portmap/assets/6510436/edada5ed-68a4-4090-b460-101c8c10c6c2)
![Screenshot from 2024-05-13 12-39-20](https://github.com/dtinit/portmap/assets/6510436/7728d089-6e68-49ea-a20b-70dcee038336)

How it should look:
![Screenshot from 2024-05-13 12-39-59](https://github.com/dtinit/portmap/assets/6510436/ca91c2b6-2039-45fc-8da2-7108d73d82a4)

**Comment by aaronjae22** [comment]
It's already looking like that in the portability articles repo though.

<img width="689" alt="image" src="https://github.com/dtinit/portmap/assets/71613005/1676b85d-2b47-4919-8f21-fec03d3fbbf9">

**Comment by alexbainter** [comment]
@aaronjae22 Right, but that's using GitHub's markdown display which is working properly. On https://portmap.dtinit.org/articles/photos2.md/ it's not displaying correctly, which means there's something wrong with the way we transform markdown to HTML.

**Comment by alexbainter** [comment]
Another example:
![image](https://github.com/dtinit/portmap/assets/6510436/5b658250-c435-4bbd-ae84-009f16334066)

**Comment by aaronjae22** [comment]
Ohh, you're absolutely right. It works fine in GitHub but Portmap does not display it as expected
